#!/bin/bash

# Remove old value, from (1) .bashrc and (2) current shell (and it's children):
line_nr=$(egrep -n '^export RHOST=' ~/.bashrc | cut -d ':' -f 1 | head -n 1)
sed -i -e $line_nr'd' ~/.bashrc
unset RHOST
./please-run-bash