#!/bin/bash

########################################
# Stuff to run on a fresh THM Kali box #
########################################

cd ~

P_THM='/root/thm'

rm -rf ~/thinclient_drives
rm -rf $P_THM 2> /dev/null

# Get decent ~/.bashrc in root's home dir:
cp /home/kali/.bashrc ~

# Make seperate dir for this THM session:
mkdir -p $P_THM

# Make seperate dir for scripts:
P_SCR=$P_THM/scripts
mkdir -p $P_SCR

# Make seperate dir for ELF binaries:
P_BIN=$P_THM/bin
mkdir -p $P_BIN

# Make sure apt repos know of latest versions:
apt update
apt autoremove

# Selective get packages to lastest version:
apt install metasploit-framework

# Make sure all gems are present for msf:
cd /usr/share/metasploit-framework
gem install bundler
gem update --system
bundle install

cd ~

# Install missing packages:
apt install gobuster
apt install tree
apt install htop
apt install screenfetch

# Setting aliases:
echo "alias ll='ls -l'" >> ~/.bashrc
echo "alias la='ls -la'" >> ~/.bashrc

# Get own GH scripts:
for s in lhost rhost please-run-bash clear-lhost clear-rhost reset-lhost reset-rhost filter-by-length get-linenum; do
	fp="$P_SCR/$s"
	wget -O "$fp" "https://raw.githubusercontent.com/m-dyson/scripts/master/$s"
	chmod 700 "$fp"
done

# Get moar wordlists:
wget https://raw.githubusercontent.com/danielmiessler/SecLists/master/Usernames/Names/names.txt \
 	-O /usr/share/wordlists/usernames-large.txt

wget https://raw.githubusercontent.com/danielmiessler/SecLists/master/Usernames/top-usernames-shortlist.txt
	-O /usr/share/wordlists/usernames-small.txt

# Make sure scripts are in $PATH:
echo "export PATH=$P_SCR:$PATH" >> ~/.bashrc

# Make sure that rerunning bash after clearing R/LHOST vars doesn't inherit
# values from parent process:
echo "unset RHOST; unset LHOST" >> ~/bashrc

# Write LHOST/RHOST to ~/.bashrc. Requires another cmd (e.g "bash") to get
# the vars in your current shell session!
$P_SCR/lhost --force
$P_SCR/rhost --force

# Attend user to rerun bash:
$P_SCR/please-run-bash

echo "NB! Please inspect ~/.bashrc if everything went OK..."
echo