#!/bin/bash

########################################
# Stuff to run on a fresh THM Kali box #
########################################

cd ~

P_THM='/root/thm'

rm -rf ~/thinclient_drives
rm -rf $P_THM 2> /dev/null

# Get decent ~/.bashrc in root's home dir:
cp /home/kali/.bashrc ~

# Make seperate dir for this THM session:
mkdir -p $P_THM

# TMP: check if dir creation succeeded:
[ -d "/root/thm" ] && echo "SUCCESS: Directory /root/thm exists." \
	|| (echo "ERROR: Directory /root/thm does not exist!" && exit 1)

# Make seperate dir for scripts:
P_SCR="$P_THM"'/scripts'
mkdir -p $P_SCR

# TMP: check if dir creation succeeded:
[ -d "/root/thm/scripts" ] && echo "SUCCESS: Directory /root/thm/scripts exists." \
	|| (echo "ERROR: Directory /root/thm/scripts does not exist!" && exit 1)

# Make sure apt repos know of latest versions:
apt update
apt autoremove

# Install missing packages:
apt install gobuster
apt install tree

# Setting aliases:
echo "alias ll='ls -l'" >> ~/.bashrc
echo "alias la='ls -la'" >> ~/.bashrc

# Get own GH scripts:
for s in lhost rhost please-run-bash clear-lhost clear-rhost reset-lhost reset-rhost; do
	fp="$P_SCR/$s"
	wget -O "$fp" "https://raw.githubusercontent.com/m-dyson/scripts/master/$s"
	chmod 700 "$fp"
done

# Make sure scripts are in $PATH:
echo "export PATH=$P_SCR:$PATH" >> ~/.bashrc

# Write LHOST/RHOST to ~/.bashrc. Requires another cmd (e.g "bash") to get
# the vars in your current shell session!
"$P_SCR/lhost" --force
"$P_SCR/rhost" --force

# Attend user to rerun bash:
"$P_SCR/please-run-bash"