#!/bin/bash

P_THM='/root/thm'
P_SCR="$P_THM"'/scripts'

# Remove old value, from (1) .bashrc and (2) current shell (and it's children):
$P_SCR/clear-rhost

# Use exiting script to set new value:
$P_SCR/rhost