#!/bin/bash

# List RHOST if already set, else (1) write to ~/.bash_profile for following
# shells and (2) echo statement for manual copying.

if [ -z "$RHOST" ]; then
	echo "The var RHOST is not set. Please enter IP for target machine:"
	echo -n ">>> "
	read rhost
	echo "Use new value: $rhost? [y/n]"
	echo -n ">>> "
	read confirmation
	if [ "${confirmation:0:1}" == 'y' ] || [ "$1" == '--force' ]; then
		echo "OK, using new value for RHOST"
		str="export RHOST=$rhost"
		echo "$str" >> ~/.bashrc
		echo "Updated ~/.bashrc -> for now, please copy and run:"
		echo
		echo "$str"
		echo
	else
		echo "Abort"
	fi
else
	echo "RHOST=$RHOST"
fi

