#!/bin/bash

P_THM=/root/thm
P_SCR=$P_THM/scripts

# Remove old value from ~/.bashrc
$P_SCR/clear-lhost

echo "Please enter new value for LHOST -> the (local) IP for the Kali machine:"
echo -n ">>> "
read lhost
echo "Use new value: $lhost? [y/n]"
echo -n ">>> "

if [ "${confirmation:0:1}" == "y" ]; then
	echo "OK, using new value for LHOST"
	str="export LHOST=$lhost"
	echo "$str" >> ~/.bashrc
	echo "Updated ~/.bashrc"
	$P_SCR/please-run-bash
else
	echo "Abort"
fi